SELECT USER_ID, USERNAME, ACCOUNT_STATUS, 
DEFAULT_TABLESPACE, TEMPORARY_TABLESPACE, CREATED, LAST_LOGIN
FROM DBA_USERS;

SELECT USER_ID, USERNAME, ACCOUNT_STATUS, 
DEFAULT_TABLESPACE, TEMPORARY_TABLESPACE, CREATED, LAST_LOGIN
FROM DBA_USERS
WHERE USER_ID = {placeholder};

SELECT USER_ID, USERNAME, ACCOUNT_STATUS, 
DEFAULT_TABLESPACE, TEMPORARY_TABLESPACE, CREATED, LAST_LOGIN
FROM DBA_USERS
WHERE USERNAME = {placeholder};

DROP USER {placeholder} CASCADE;

GRANT CONNECT TO {placeholder} IDENTIFIED BY {placeholder};